map_size: 30 #[width, height] size of the map
start_position: [0, 0, 0]   # The x and y location of the start point
goal_position: [29,29 , 29] #The x and y location of the goal point
obstacles: [ [2,2,5]]
hidden_obstacles: [[15,15,15], [28,28, 28], [17,15, 15], [18,15, 15], [19, 15, 15]]
#  [[15,15], [16,15], [17,15], [18,15], [19, 15], [20, 15], [21, 15], [22,15], [22,14], [22, 13], [22, 12], [22, 11], [22,10], [22,9], [22, 8], [22, 7]]
max_thread: 4096 #The maximum thread of GPU can be used for the planning. AKA the maximum number of nodes can be explored each time
use_parallel: 1 #Determine if we are using parallel planning or no